name: CI

on:
  workflow_dispatch:

jobs:
  slack-notify:
    runs-on: ubuntu-latest
    env: 
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Notify Slack - Workflow Started 🚀
        uses: act10ns/slack@v2
        with:
          status: starting
          message: |
            🚀 *GitHub Action Workflow Started:* `Deploy to Amazon ECS`
            *Commit:* `${{ github.sha }}`
            *Triggered by:* `${{ github.actor }}`

      - name: Notify Slack - Completion
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          message: |
            ${{ job.status == 'success' && ':white_check_mark: *Deployment Successful!* :tada:' || ':x: *Deployment Failed!* :boom:' }}
            *Workflow:* `Deploy to Amazon ECS`
            *Status:* `${{ job.status }}`
            *Commit:* `${{ github.sha }}`
            *View Details & Logs:* <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>
        if: always()
