name: CI

on:
  workflow_dispatch:

jobs:
  notify-start:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Send Slack Notification - Started 🚀
        uses: act10ns/slack@v2
        with:
          status: starting
          message: |
            🚀 *GitHub Action Workflow Started:* `${{ github.workflow }}`
            *Repository:* `${{ github.repository }}`
            *Branch:* `${{ github.ref_name }}`
            *Commit:* `${{ github.sha }}`
            *Triggered by:* `${{ github.actor }}`

  main-job:
    needs: notify-start
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Example real task
        run: |
          echo "Add real deployment/build steps here"

  slack-notify:
    needs: main-job
    runs-on: ubuntu-latest
    timeout-minutes: 2
    if: always()
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Send Slack Notification - Final Status ✅❌
        uses: act10ns/slack@v2
        with:
          status: ${{ needs.main-job.result }}
          message: |
            ${{ needs.main-job.result == 'success' && ':white_check_mark: *Deployment Successful!* :tada:' || ':x: *Deployment Failed!* :boom:' }}
            *Workflow:* `${{ github.workflow }}`
            *Repository:* `${{ github.repository }}`
            *Branch:* `${{ github.ref_name }}`
            *Status:* `${{ needs.main-job.result }}`
            *Commit:* `${{ github.sha }}`
            🔗 *View Details & Logs:* <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>
