name: CI

on:
  workflow_dispatch:

jobs:
  force-fail:
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Send Slack Notification - Started 🚀
        uses: act10ns/slack@v2
        with:
          status: starting
          message: |
            🚀 *GitHub Action Workflow Started:* `${{ github.workflow }}`
            *Repository:* `${{ github.repository }}`
            *Branch:* `${{ github.ref_name }}`
            *Commit:* `${{ github.sha }}`
            *Triggered by:* `${{ github.actor }}`

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate failure 💣
        run: |
          echo "This job will now fail intentionally."
          exit 1

  slack-notify:
    needs: force-fail
    runs-on: ubuntu-latest
    if: always()
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Send Slack Notification - Final Status ✅❌
        uses: act10ns/slack@v2
        with:
          status: ${{ needs.force-fail.result }}
          message: |
            ${{ needs.force-fail.result == 'success' && ':white_check_mark: *Deployment Successful!* :tada:' || ':x: *Deployment Failed!* :boom:' }}
            *Workflow:* `${{ github.workflow }}`
            *Repository:* `${{ github.repository }}`
            *Branch:* `${{ github.ref_name }}`
            *Status:* `${{ needs.force-fail.result }}`
            *Commit:* `${{ github.sha }}`
            🔗 *View Details & Logs:* <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>
